apiVersion: v1
kind: ConfigMap
metadata:
  name: bidw-auth-config
data:
  SERVER_PORT: "8080"
  POSTGRES_HOST: "postgres-auth-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "authdb"
  ALLOWED_ORIGINS: "http://localhost:3000,http://20.214.99.23"
